### PR TITLE
fix vcmap to work with tbb2021.1.1

### LINKED ISSUE #894: ISSUE: vcmap does not work with latest tbb (2021.1)
# ISSUE: vcmap does not work with latest tbb (2021.1)

## Environment Information

- pmemkv version(s):                                                 1.0/1.1/1.2/1.3/master
- libpmemobj-cpp version(s):                                         
- PMDK (libpmem/libpmemobj) package version(s):                      
- OS(es) version(s):                                                 
- kernel version(s):                                                 
- compiler, libraries, packaging and other related tools version(s): 

and possibly:
- TBB version(s):                                                   2021.1
- memkind version(s):                                                
- ndctl version(s):                                                  

## Please provide a reproduction of the bug:

```
/home/igor/installed/tbb-2021-1.1-lock/include/tbb/../oneapi/tbb/concurrent_hash_map.h:785:31: error: call to implicitly-deleted default constructor of 'tbb::detail::d1::tbb_hash_compare<std::__cxx11::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >'
        : concurrent_hash_map(HashCompare(), a)

```

## How often bug is revealed:

always

## Actual behavior:

Compilation fails

## Expected behavior:

Compilation passes

## Details

It looks like tbb specialization for std::hash<std::basic_string> is not found. Maybe this has something to do with our build system - standalone program with tbb::concurrent_hash_map and std::basic_string with memkind allocator works fine.

After fixing this, we should add a CI build with latest tbb.

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

### PR DESCRIPTION
**Pull request by JanDorniak99**
fixes #894

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv/935)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
maybe we should put it on stable branch..?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/935#-:-MTeYlXv-AQxgoC-Arje:b-5c9cz7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by igchor — COMMENTED** [review]
Yeah, I think we should (1.5?)

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/935#-:-MTf-y-GEaZUxCeIkc6h:bjcgcg6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Comment by lukaszstolarczuk** [comment]
> Yeah, I think we should (1.5?)
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemkv/935#-:-MTf-y-GEaZUxCeIkc6h:bjcgcg6)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

it's pmemkv :D - so I'd say 1.1
And we'll make patch releases soon so it will be included in all our branches right away..
